ProductDemo/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Newtonsoft.Json;
using ProductDemo.Interface;
using ProductDemo.Models;
using System.Text;

namespace ProductDemo.Controllers
{
    public class CartController : Controller
    {
        private const string MerchantKey = "srPlMt";
        private const string MerchantSalt = "kUG7FpuDkRzDcPkZPJmBlcAa6DnceZBu";
        private const string PayUBaseURL = "https://test.payu.in/_payment";

        private readonly ICartService _cartService;
        private readonly ProductDB _productDB;
        private readonly IConfiguration _configuration;

        public CartController(ICartService cartService, ProductDB productDB, IConfiguration configuration)
        {
            _cartService = cartService;
            _productDB = productDB;
            _configuration = configuration;
        }

        public IActionResult Index()
        {
            var cartItems = _cartService.GetCartItems();
            return View(cartItems);
        }

        [HttpPost]
        public async Task<IActionResult> AddtoCart(int Pro_Id)
        {
            var product = await GetProductById(Pro_Id);
            if (product != null)
            {
                _cartService.AddToCart(product);

            }
            _productDB.SaveChanges();
            return RedirectToAction("Index");
        }

        public async Task<Products> GetProductById(int id)
        {
            return await _productDB.Products.FirstOrDefaultAsync(p => p.Pro_Id == id);
        }

        public IActionResult CheckOut(Products products)
        {
            var cartitem = _cartService.GetCartItems();
            var totalAmount = cartitem.Sum(item => item.Pro_Prize * item.Quantity);

            ViewBag.TotalAmount = totalAmount;
            ViewBag.CartItem = cartitem;
            return View(cartitem);
        }

    }
    
}
 

ProductDemo/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProductDemo.Models;

namespace ProductDemo.Controllers
{
    public class ProductsController : Controller
    {
        private readonly ProductDB _context;

        public ProductsController(ProductDB context)
        {
            _context = context;
        }

        // GET: Products
        public async Task<IActionResult> Index()
        {
            return View(await _context.Products.ToListAsync());
        }

        // GET: Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await GetProductById(id.Value);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Products/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Pro_Id,Pro_Name,Pro_Prize")] Products products)
        {
            if (ModelState.IsValid)
            {
                _context.Add(products);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(products);
        }

        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await GetProductById(id.Value);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Pro_Id,Pro_Name,Pro_Prize")] Products products)
        {
            if (id != products.Pro_Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(products);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductsExists(products.Pro_Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(products);
        }

        // GET: Products/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await GetProductById(id.Value);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await GetProductById(id);
            if (product != null)
            {
                _context.Products.Remove(product);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductsExists(int id)
        {
            return _context.Products.Any(e => e.Pro_Id == id);
        }

        public async Task<Products> GetProductById(int id)
        {
            return await _context.Products.FirstOrDefaultAsync(p => p.Pro_Id == id);
        }
    }
}

ProductDemo/Views/Cart/CheckOut.cshtml
@model IEnumerable<ProductDemo.Models.CartItem>

@{
    ViewData["Title"] = "CheckOut";
}

<h1>CheckOut</h1>

@* <p>
    <a asp-action="Create">Create New</a>
</p> *@
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Pro_Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pro_Prize)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th> Total</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Pro_Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pro_Prize)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
                @(item.Pro_Prize * item.Quantity)
            </td>
          @*   <td>
                <a asp-action="Edit" asp-route-id="@item.Pro_Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Pro_Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Pro_Id">Delete</a>
            </td> *@
        </tr>
}

        <h3>Total Amount: @ViewBag.TotalAmount</h3>

        <form asp-controller="Payment" asp-action="ProcessPayment" method="post">
            <div class="form-group">
                <label for="firstname">First Name</label>
                <input type="text" id="firstname" name="FirstName" class="form-control" required />
            </div>
            <div class="form-group">
                <label for="email">Email</label>
                <input type="email" id="email" name="Email" class="form-control" required />
            </div>
            <div class="form-group">
                <label for="address">Address</label>
                <input type="text" id="address" name="address" class="form-control" required />
            </div>
            <div class="form-group">
                <label for="phone">Phone</label>
                <input type="text" id="phone" name="Phone" class="form-control" required />
            </div>
            <button type="submit" class="btn btn-primary">Proceed to Payment</button>
        </form>

       @*  <form asp-controller="Cart" asp-action="ProccessPayment" method="post">
            <button type="submit" class="btn btn-primary">Proceed to Payment</button>
        </form> *@
    </tbody>
</table>

ProductDemo/Views/Cart/Index.cshtml
@model IEnumerable<ProductDemo.Models.CartItem>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-controller="Products" asp-action="Index" class="btn btn-primary">Continue Shopping</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Pro_Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pro_Prize)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th>
                   Total
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Pro_Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pro_Prize)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
                <td>
                    @(item.Pro_Prize * item.Quantity)
                </td>
            @* <td>
                <a asp-action="Edit" asp-route-id="@item.Pro_Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Pro_Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Pro_Id">Delete</a>
            </td> *@
                <a asp-controller="Cart" asp-action="CheckOut" class="btn btn-success">Proceed to Checkout</a>
        </tr>
}
    </tbody>
</table>